package com.smartmealplanner.auth.application;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.time.Clock;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.smartmealplanner.auth.persistence.SecurityTokenKind;
import com.smartmealplanner.auth.persistence.UserAccount;
import com.smartmealplanner.auth.persistence.UserSecurityToken;
import com.smartmealplanner.auth.persistence.UserSecurityTokenRepository;

@Service
public class SecurityTokenService {

    private static final int TOKEN_BYTES = 32;
    private static final int TOKEN_HEX_LENGTH =
            TOKEN_BYTES * 2;

    private static final Duration EMAIL_VERIFICATION_TTL =
            Duration.ofHours(24);

    private static final Duration PASSWORD_RESET_TTL =
            Duration.ofHours(1);

    private final UserSecurityTokenRepository tokens;
    private final SecureRandom secureRandom;
    private final Clock clock;

    public SecurityTokenService(
            UserSecurityTokenRepository tokens) {

        this.tokens = tokens;
        this.secureRandom = new SecureRandom();
        this.clock = Clock.systemUTC();
    }

    @Transactional
    public String createEmailVerificationToken(
            UserAccount account) {

        return createExclusiveToken(
                account,
                SecurityTokenKind.EMAIL_VERIFICATION,
                EMAIL_VERIFICATION_TTL);
    }

    @Transactional
    public String createPasswordResetToken(
            UserAccount account) {

        return createExclusiveToken(
                account,
                SecurityTokenKind.PASSWORD_RESET,
                PASSWORD_RESET_TTL);
    }

    public String hashToken(
            String plaintextToken) {

        if (plaintextToken == null) {
            throw new IllegalArgumentException(
                    "token is required");
        }

        String normalizedToken =
                plaintextToken
                        .trim()
                        .toLowerCase(Locale.ROOT);

        if (normalizedToken.length()
                != TOKEN_HEX_LENGTH) {

            throw new IllegalArgumentException(
                    "token length is invalid");
        }

        return sha256Hex(
                normalizedToken);
    }

    public LocalDateTime nowUtc() {

        return LocalDateTime.ofInstant(
                clock.instant(),
                ZoneOffset.UTC);
    }

    private String createExclusiveToken(
            UserAccount account,
            SecurityTokenKind tokenKind,
            Duration ttl) {

        if (account == null
                || account.internalId() == null) {

            throw new IllegalArgumentException(
                    "persisted account is required");
        }

        /*
         * issued_at is generated by MySQL, so derive expires_at from the
         * same database clock. This avoids JVM/database timezone drift.
         */
        LocalDateTime databaseNow =
                tokens.currentDatabaseTime();

        /*
         * Pessimistic locking requires an active transaction. The two
         * public token-creation methods are therefore transactional even
         * when called directly from tests or future application services.
         */
        List<UserSecurityToken> outstandingTokens =
                tokens.findOutstandingByUserIdAndKindForUpdate(
                        account.internalId(),
                        tokenKind);

        for (UserSecurityToken token :
                outstandingTokens) {

            if (!token.isConsumed()) {
                token.consume(
                        databaseNow);
            }
        }

        byte[] randomBytes =
                new byte[TOKEN_BYTES];

        secureRandom.nextBytes(
                randomBytes);

        String plaintextToken =
                HexFormat.of()
                        .formatHex(
                                randomBytes);

        String tokenHash =
                hashToken(
                        plaintextToken);

        UserSecurityToken token =
                new UserSecurityToken(
                        account,
                        tokenKind,
                        tokenHash,
                        databaseNow.plus(
                                ttl));

        tokens.saveAndFlush(
                token);

        return plaintextToken;
    }

    private static String sha256Hex(
            String value) {

        try {
            MessageDigest digest =
                    MessageDigest.getInstance(
                            "SHA-256");

            return HexFormat.of()
                    .formatHex(
                            digest.digest(
                                    value.getBytes(
                                            StandardCharsets.UTF_8)));

        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException(
                    "SHA-256 is not available",
                    exception);
        }
    }
}
