"""Bounded transport limits for meal-planning contract version 1."""

CONTRACT_VERSION = "1"

MAX_PLAN_DAYS = 7
MAX_REQUESTED_MEAL_SLOTS = 6
MAX_EXPANDED_PLAN_SLOTS = MAX_PLAN_DAYS * MAX_REQUESTED_MEAL_SLOTS

MAX_ALLERGEN_CODES = 32
MAX_DIETARY_CODES = 32
MAX_PREFERENCE_CODES = 32
MAX_INGREDIENT_PREFERENCE_IDS = 500
MAX_NUTRITION_TARGETS = 64
MAX_UNIT_DEFINITIONS = 128
MAX_PANTRY_LOTS = 2_000
MAX_INGREDIENT_FACTS = 2_500
MAX_ALLERGEN_FACTS_PER_INGREDIENT = 64
MAX_RECIPE_CANDIDATES = 200
MAX_INGREDIENTS_PER_RECIPE = 50
MAX_RECIPE_TAG_CODES = 64
MAX_NUTRITION_VALUES_PER_RECIPE = 64
MAX_SCORE_COMPONENTS = 7
MAX_EXPLANATION_LENGTH = 500
MAX_REQUEST_BYTES = 5 * 1024 * 1024

# Beam-width ceiling; deployment configuration is not a V1 request field.
MAX_FUTURE_BEAM_WIDTH = 50

MAX_MINUTES_PER_MEAL = 1_440
MAX_REFERENCE_CODE_LENGTH = 64
REFERENCE_CODE_PATTERN = r"^[A-Z][A-Z0-9_]{0,63}$"
