package com.smartmealplanner.mealplanning.persistence;

import java.util.Optional;
import jakarta.persistence.LockModeType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Lock;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

public interface RecommendationRequestRepository extends JpaRepository<RecommendationRequest, Long> {
    Optional<RecommendationRequest> findByPublicId(byte[] publicId);

    @Lock(LockModeType.PESSIMISTIC_WRITE)
    @Query("select request from RecommendationRequest request where request.id = :requestId")
    Optional<RecommendationRequest> findByIdForUpdate(@Param("requestId") Long requestId);

    // requested_at is generated by MySQL; set completed_at on the same clock to avoid
    // a DB -> JVM -> Hibernate time-zone conversion before the completion-order check.
    @Modifying(flushAutomatically = true)
    @Query(value = """
            UPDATE recommendation_requests
            SET status = :status, completed_at = CURRENT_TIMESTAMP(6),
                duration_ms = :durationMs, failure_reason = :failureReason
            WHERE id = :requestId AND request_kind = 'MEAL_PLAN' AND status = 'PENDING'
            """, nativeQuery = true)
    int completePending(@Param("requestId") Long requestId,
            @Param("status") String status,
            @Param("durationMs") Integer durationMs,
            @Param("failureReason") String failureReason);
}
